### ISSUE TITLE
Unofficial implementation claririfation

### ISSUE THREAD

**Issue by dorarad** [FutureXiang/soda#2]
Hey there, thank you very much for working on this repo! I highly appreciate it!

I wanted to ask if you could please add in the title of the github page (the readme file) that his is unofficial implementation please?
I've seen it's mentioned in the about section but that might be quite hard to notice.

I'm also planning to release an official version soon.

Thanks a lot!
- Drew

**Comment by FutureXiang** [comment]
Of course, glad to see the official one coming out!
